name: Hello World!

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Run a one-line script
        run: echo Hello, world!
